### ISSUE TITLE
Rendered some transforms

### ISSUE THREAD

**Issue by miyamoen** [mdgriffith/style-elements#131]
My style looks like this:
```elm
style MyStyle
            [ translate 0 -30 0
            , scale 0.7 0.7 1
            , variation MyVariation
                [ rotate <| degrees 180
                , translate 0 30 0
                , scale 0.7 0.7 1
                ]
            ]
```
I expected this style is rendered like this:
```css
.style-elements .my-style-my-variation__956448198 {
    transform: rotate(3.141592653589793rad) translate3d(0px, 30px, 0px) scale3d(0.7, 0.7, 1);
}
```
But actual is:
```css
.style-elements .my-style-my-variation__956448198 {
    transform: rotate(3.141592653589793rad);
    transform: translate3d(0px, 30px, 0px);
    transform: scale3d(0.7, 0.7, 1);
}
```
This does not work as expected.

https://github.com/mdgriffith/style-elements/blob/2c4585dcb20090d60459f6d8d0c2506398957284/src/Style/Internal/Render.elm#L118
`Style.Internal.Render.preprocess` does not process `Style.Internal.Model.Variation` and `Style.Internal.Model.PseudoElement` branches.

I want to process...

## Versions

- Elm:0.18
- style-elements: 4.2.1
- Operating System: windows 10
